# Generated by Django 5.1.6 on 2025-03-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='video',
        ),
    ]
