# Generated by Django 5.1.6 on 2025-03-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Service', '0003_alter_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.DecimalField(decimal_places=0, max_digits=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.DecimalField(decimal_places=0, max_digits=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='master',
            name='master_id',
            field=models.DecimalField(decimal_places=0, max_digits=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.DecimalField(decimal_places=0, max_digits=100, primary_key=True, serialize=False),
        ),
    ]
