# Generated by Django 5.2.1 on 2025-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Service', '0003_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
