# Generated by Django 5.1.6 on 2025-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Service', '0004_alter_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='qualification',
        ),
        migrations.AddField(
            model_name='master',
            name='experience',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
