# Generated by Django 5.1.6 on 2025-03-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Service', '0005_remove_master_qualification_master_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='age',
        ),
    ]
