# Generated by Django 5.1.6 on 2025-03-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Service', '0006_remove_master_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='login',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='master',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
