# Generated by Django 5.1.6 on 2025-03-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto_Service', '0007_alter_master_login_alter_master_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
